import type { CollectionItem } from "./types";

const now = "2026-09-20T00:00:00.000Z";

/** Deletable sample Xbox One entries so the shelf isn't empty on first visit. */
export const SAMPLE_ITEMS: CollectionItem[] = [
  {
    id: "sample-halo-5",
    title: "Halo 5: Guardians",
    platform: "xbox-one",
    media: "physical",
    condition: "cib",
    quantity: 1,
    purchasePriceAud: 8,
    purchaseDate: "2026-09-01",
    notes: "SAMPLE — delete me when you add your real disks.",
    barcode: "",
    region: "PAL",
    edition: "",
    itemKind: "game",
    estimatedMarketValueAud: null,
    coverArtUrl: "",
    status: "owned",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-forza-h3",
    title: "Forza Horizon 3",
    platform: "xbox-one",
    media: "physical",
    condition: "cib",
    quantity: 1,
    purchasePriceAud: 40,
    purchaseDate: "2026-09-10",
    notes: "SAMPLE — typical Xbox One disk entry.",
    barcode: "",
    region: "PAL",
    edition: "",
    itemKind: "game",
    estimatedMarketValueAud: null,
    coverArtUrl: "",
    status: "owned",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-gears-4",
    title: "Gears of War 4",
    platform: "xbox-one",
    media: "physical",
    condition: "loose",
    quantity: 1,
    purchasePriceAud: null,
    purchaseDate: null,
    notes: "SAMPLE — loose disk, no purchase price logged.",
    barcode: "",
    region: "PAL",
    edition: "",
    itemKind: "game",
    estimatedMarketValueAud: null,
    coverArtUrl: "",
    status: "owned",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-minecraft",
    title: "Minecraft",
    platform: "xbox-one",
    media: "physical",
    condition: "new-sealed",
    quantity: 1,
    purchasePriceAud: 15,
    purchaseDate: "2026-09-15",
    notes: "SAMPLE — sealed copy.",
    barcode: "",
    region: "PAL",
    edition: "",
    itemKind: "game",
    estimatedMarketValueAud: null,
    coverArtUrl: "",
    status: "owned",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-xbox-one",
    title: "Xbox One",
    platform: "xbox-one",
    media: "physical",
    condition: "good",
    quantity: 1,
    purchasePriceAud: 120,
    purchaseDate: "2026-09-18",
    notes: "SAMPLE hardware — console in the same catalog as games.",
    barcode: "",
    region: "PAL",
    edition: "Day One",
    itemKind: "hardware",
    estimatedMarketValueAud: null,
    coverArtUrl: "",
    status: "owned",
    isSample: true,
    createdAt: now,
    updatedAt: now,
  },
];
